[package]
name = "zero2prod"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
cargo-watch = "8.5.3"  # automate the process of checking, testing, and running your code
cargo-tarpaulin = "0.31.2"  # code coverage
